version: '3.9'

services:
  postgres_db:
    image: postgres:15
    container_name: yakhteh_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yakhteh_net

  redis_cache:
    image: redis:7
    container_name: yakhteh_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - yakhteh_net

  auth_service:
    build:
      context: ./services/auth_service
      dockerfile: Dockerfile
    container_name: yakhteh_auth_service
    restart: unless-stopped
    depends_on:
      - postgres_db
      - redis_cache
    env_file:
      - .env
    environment:
      # Service-specific overrides can go here
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8001:8000"
    networks:
      - yakhteh_net

  clinic_service:
    build:
      context: ./services/clinic_service
      dockerfile: Dockerfile
    container_name: yakhteh_clinic_service
    restart: unless-stopped
    depends_on:
      - postgres_db
      - redis_cache
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8002:8000"
    networks:
      - yakhteh_net

volumes:
  postgres_data:

networks:
  yakhteh_net:
    driver: bridge
