log:
  level: INFO

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

# Static TLS certificates (user-provided). Traefik will serve these files for matching SNI.
tls:
  certificates:
    - certFile: /certs/chizmarket.crt
      keyFile: /certs/chizmarket.key
